"""keyboardforge_core.xkb_generator

Generates the two text artifacts the Linux installer consumes from a
Layout: the XKB symbols file (`xkb_symbols "<variant>" { ... }`) and the
XML `<layout>` rules stub injected into evdev.xml.
"""

from __future__ import annotations

from xml.sax.saxutils import escape

from .model import Layout
from .validator import validate, has_errors


class LayoutGenerationError(Exception):
    pass


def generate_symbols_file(layout: Layout) -> str:
    """Render the XKB `xkb_symbols` block for this layout."""
    issues = validate(layout)
    if has_errors(issues):
        details = "\n".join(f"  - {i}" for i in issues if i.severity == "error")
        raise LayoutGenerationError(
            f"Cannot generate '{layout.xkb_name}': layout has validation errors:\n{details}"
        )

    lines = []
    lines.append(f"# {layout.xkb_name}")
    lines.append(f"# XKB symbols generated by KeyboardForge from {layout.xkb_name}.json")
    if layout.author:
        lines.append(f"# Author: {layout.author}")
    lines.append(f"# Do not edit by hand -- regenerate with tools/generate_layout.py")
    lines.append("")
    lines.append("default partial alphanumeric_keys")
    lines.append(f'xkb_symbols "{layout.variant}" {{')
    lines.append("")
    lines.append(f'    name[Group1]= "{layout.description}";')
    if layout.base_layout:
        lines.append(f'    include "{layout.base_layout}"')
    lines.append("")

    for keycode in sorted(layout.keys.keys()):
        key = layout.keys[keycode]
        syms = ", ".join(key.levels)
        comment = f"  // {key.comment}" if key.comment else ""
        lines.append(f"    key <{keycode}> {{ [ {syms} ] }};{comment}")

    if layout.includes:
        lines.append("")
        for inc in layout.includes:
            lines.append(f'    include "{inc}"')

    lines.append("};")
    lines.append(f"# Author: {layout.author}" if layout.author else "")
    return "\n".join(line for line in lines if line is not None).rstrip() + "\n"


def generate_rules_xml(layout: Layout) -> str:
    """Render the `<layout>` XML stub injected into evdev.xml."""
    issues = validate(layout)
    if has_errors(issues):
        details = "\n".join(f"  - {i}" for i in issues if i.severity == "error")
        raise LayoutGenerationError(
            f"Cannot generate rules for '{layout.xkb_name}': layout has validation errors:\n{details}"
        )

    xkb_name = escape(layout.xkb_name)
    variant = escape(layout.variant)
    description = escape(layout.description)
    short_desc = escape(layout.xkb_name.replace("_", "-"))
    language = escape(layout.language)

    return (
        f"<!-- rules -->\n"
        f"<!-- {xkb_name} rules entry for evdev.xml -->\n"
        f"<!-- Generated by KeyboardForge -->\n\n"
        f"<layout>\n"
        f"  <configItem>\n"
        f"    <name>{xkb_name}</name>\n"
        f"    <shortDescription>{short_desc}</shortDescription>\n"
        f"    <description>{description}</description>\n"
        f"    <languageList>\n"
        f"      <iso639Id>{language}</iso639Id>\n"
        f"    </languageList>\n"
        f"  </configItem>\n"
        f"  <variantList>\n"
        f"    <variant>\n"
        f"      <configItem>\n"
        f"        <name>{variant}</name>\n"
        f"        <description>{description}</description>\n"
        f"      </configItem>\n"
        f"    </variant>\n"
        f"  </variantList>\n"
        f"</layout>\n"
    )


def generate(layout: Layout, output_dir: str) -> dict:
    """Write both artifacts to output_dir. Returns the paths written.

    The symbols file is named after `layout.xkb_name` (matching XKB's own
    convention that the symbols filename IS the layout identifier). The
    rules stub is always named "rules", matching what linux/install.sh
    expects to find and inject.
    """
    import os

    symbols_path = os.path.join(output_dir, layout.xkb_name)
    rules_path = os.path.join(output_dir, "rules")

    with open(symbols_path, "w", encoding="utf-8") as f:
        f.write(generate_symbols_file(layout))
    with open(rules_path, "w", encoding="utf-8") as f:
        f.write(generate_rules_xml(layout))

    return {"symbols": symbols_path, "rules": rules_path}
